# Generated by Django 3.2 on 2022-08-15 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20220814_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image_url',
            field=models.ImageField(blank=True, upload_to='book_images'),
        ),
    ]
