# Generated by Django 3.2 on 2022-08-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_is_bestseller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='book_is_new',
            field=models.BooleanField(default=True),
        ),
    ]
