# Generated by Django 3.2 on 2022-08-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_cart_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
