# Generated by Django 3.2.3 on 2022-07-24 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Genre',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='Publisher',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='SeriesBooks',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
